[registries.crates-io]
protocol = "sparse"

[build]
# target = ["x86_64-unknown-linux-musl"]
# target = ["x86_64-unknown-linux-gnu"]
# target = ["aarch64-linux-android"] # arm64-v8a 
# target = ["armv7-linux-androideabi"] # armeabi-v7a 
# target = ["i686-linux-android"] # x86
# target = ["x86_64-linux-android"] # x86_64
# target = ["aarch64-apple-ios"]
# target = ["x86_64-pc-windows-msvc"]
# target = ["x86_64-apple-darwin"]
# target = ["x86_64-unknown-freebsd"]
